version: "3.9"

services:
  nats-server:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222" # HTTP monitoring port
    networks:
      - nats-net

networks:
  nats-net:
    driver: bridge
