version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: my_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:


networks:
  my_network:
